#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Set the default settings of the service package to those expected
        # by OpenMediaVault.
        if [ -z "${2}" ]; then
            invoke-rc.d --force cups stop
            update-rc.d cups disable >/dev/null
        fi

        SERVICE_XPATH_NAME="cups"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        # Check for XML config
        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "airprint" "1"en
            omv_config_add_element "${SERVICE_XPATH}" "enable_samba" "1"
            omv_config_add_element "${SERVICE_XPATH}" "max_jobs" "100"
            omv_config_add_element "${SERVICE_XPATH}" "remote_printers" "0"
        fi

        # Add lpadmin group.
        groupadd -f lpadmin
        omv_config_update "//system/usermanagement/groups/group[name='lpadmin']/comment" "Printer administrators."

        # Silently add OpenMediaVault admin user to lpadmin group.
        usermod -G lpadmin -a admin

        # Set permissions for samba printer driver sharing.
        chgrp -R lpadmin /var/lib/samba/printers
        chmod -R g+w /var/lib/samba/printers

        # Check for en_US.UTF-8 locale and enable it.
        # TODO: It has never been stated why this is done.
        if [ "$(grep -c '^\s*en_US.UTF-8' /etc/locale.gen)" = "0" ]; then
            # If the locale is not found in the file we need to add it. If it
            # does exist we can just uncomment it with the help of sed.
            if [ "$(grep -c '^\s*#\s*en_US.UTF-8' /etc/locale.gen)" = "0" ]; then
                echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
            else
                tempFile=$(mktemp)

                cat /etc/locale.gen | sed -e 's/^\s*#\s*\(en_US.UTF-8.*\)/\1/g' > ${tempFile}
                cat ${tempFile} > /etc/locale.gen

                rm ${tempFile}
            fi

            locale-gen
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
