#!/bin/sh

set -e

case "$1" in
    install)

        # Backup cups config
        if [ ! -e /etc/cups/cupsd.conf-orig ] && [ -e /etc/cups/cupsd.conf ]; then
            /bin/cp /etc/cups/cupsd.conf /etc/cups/cupsd.conf-orig
        fi

    ;;

    upgrade|abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
